### ISSUE TITLE
About CBM,VBM, CSB and VSB KPOINTS

### ISSUE THREAD

**Issue by yjhao11** [Baijianlu/AICON2#16]
Dear Tao,
     For CBM, VBM, CSB and VSB calculation, KPOINTS generated by  difference method, How to take out that document separately from program. I want to calculate CBM ,VBM, CSB and VSB by hse method. How to generate KPOINTS file. Thank you very much!
Best  wishes,
 Y.J.Hao

**Comment by Baijianlu** [comment]
Hi，


For effective mass, I don't suggest you use HSE method to do the calculation, since it highly possible cannot be converged. If you insist doing so, it almost the same as band structure calculation using HSE. If you want generate KPOINTS file for effective mass calculation, please check emc.py file, also the related part in AICON2 paper.

________________________________
From: yjhao11 ***@***.***>
Sent: 16 May 2024 05:22:20
To: Baijianlu/AICON2
Cc: Subscribed
Subject: [Baijianlu/AICON2] About CBM,VBM, CSB and VSB KPOINTS (Issue #16)


Dear Tao,
For CBM, VBM, CSB and VSB calculation, KPOINTS generated by difference method, How to take out that document separately from program. I want to calculate CBM ,VBM, CSB and VSB by hse method. How to generate KPOINTS file. Thank you very much!
Best wishes,
Y.J.Hao

**Comment by yjhao11** [comment]
Okay, Thank you very much!

**Comment by yociftci-ux** [comment]
AICON --elec -m standard -t 300
Traceback (most recent call last):
  File "/arf/home/yciftci/.local/bin/AICON", line 83, in <module>
    Get_Electron("./", Temp, Dope, mode, ifSB)
  File "/arf/home/yciftci/.local/bin/AICON", line 44, in Get_Electron
    Compound.Get_values(filepath, Temp, dope, mode, ifSB=ifSB)
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/electron.py", line 227, in Get_values
    CBM_Elcond, CBM_Seebeck, CBM_Lorenz, CBM_Ekappa, CBM_Hallfactor, CBM_Hallcoeff, CBM_PF) = self.CBM.Get_transport_para(filep
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/band.py", line 159, in Get_transport_para
    self.RT.Get_Totaltime(filepath, ACO = True, OPT = True, IMP = True)
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/relaxtime.py", line 362, in Get_Totaltime
    self.ACO.Get_Avgacotime(filepath)
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/relaxtime.py", line 143, in Get_Avgacotime
    self.Get_relaxtimefun(filepath)
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/relaxtime.py", line 136, in Get_relaxtimefun
    self.Get_effemass(filepath)
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/relaxtime.py", line 79, in Get_effemass
    self.EMC.cal_effmass(kpt, stepsize, band, prg, basis, filepath+'EIGENVAL')
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/myemc.py", line 507, in cal_effmass
    energies = self.parse_EIGENVAL_VASP(output_fh, band, len(st))
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/myemc.py", line 372, in parse_EIGENVAL_VASP
    energies.append(float(line.split()[1])*ev2h)
IndexError: list index out of range
How can I correct this error
