### ISSUE TITLE
error:IndexError: list index out of range

### ISSUE THREAD

**Issue by yjhao11** [Baijianlu/AICON2#17]
when calculate the thermal conductivity, there are some errors.How to fix it. Thank you very much!

Traceback (most recent call last):
  File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/fireworks/core/rocket.py", line 261, in run
    m_action = t.run_task(my_spec)
  File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/myfiretasks.py", line 430, in run_task
    Get_Electron("./", Temp, Doping, mode, ifSB)
  File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/electron.py", line 38, in Get_Electron
    Compound.Get_values(filepath, Temp, dope, mode, ifSB=ifSB)
  File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/electron.py", line 291, in Get_values
    self.CBM.Get_carridensity(filepath)
  File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/band.py", line 100, in Get_carridensity
    self.Get_relaxtime(filepath)
  File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/band.py", line 90, in Get_relaxtime
    self.RT.Get_Totaltime(filepath, ACO = True, OPT = True, IMP = True)                                                      #unit: second
  File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/relaxtime.py", line 362, in Get_Totaltime
    self.ACO.Get_Avgacotime(filepath)
  File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/relaxtime.py", line 143, in Get_Avgacotime
    self.Get_relaxtimefun(filepath)
  File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/relaxtime.py", line 135, in Get_relaxtimefun
    self.Get_elastconst(filepath + 'elastic/')
  File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/relaxtime.py", line 89, in Get_elastconst
    self.Elastic.Get_AvgLongEConst(filepath)
  File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/elastic.py", line 49, in Get_AvgLongEConst
    self.Get_ElasConst(filepath)
  File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/elastic.py", line 45, in Get_ElasConst
    outcar.read_elastic_tensor()
  File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/pymatgen/io/vasp/outputs.py", line 2501, in read_elastic_tensor
    et_table = self.read_table_pattern(header_pattern, row_pattern, footer_pattern, postprocess=float)
  File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/pymatgen/io/vasp/outputs.py", line 2224, in read_table_pattern
    retained_data = tables[-1] if last_one_only or first_one_only else tables
IndexError: list index out of range

**Comment by Baijianlu** [comment]
Hi,


Apparently you are not calculating the thermal conductivity and it is electronic transport properties calculation. The error is also clear, you elastic constant calculation seems have some problem. Please check the OUTCAR file of your elastic constant calculation to see if it contains the elastic constant tensor in this file.


________________________________
From: yjhao11 ***@***.***>
Sent: 21 May 2024 03:57:45
To: Baijianlu/AICON2
Cc: Subscribed
Subject: [Baijianlu/AICON2] error:IndexError: list index out of range (Issue #17)


when calculate the thermal conductivity, there are some errors.How to fix it. Thank you very much!

Traceback (most recent call last):
File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/fireworks/core/rocket.py", line 261, in run
m_action = t.run_task(my_spec)
File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/myfiretasks.py", line 430, in run_task
Get_Electron("./", Temp, Doping, mode, ifSB)
File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/electron.py", line 38, in Get_Electron
Compound.Get_values(filepath, Temp, dope, mode, ifSB=ifSB)
File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/electron.py", line 291, in Get_values
self.CBM.Get_carridensity(filepath)
File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/band.py", line 100, in Get_carridensity
self.Get_relaxtime(filepath)
File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/band.py", line 90, in Get_relaxtime
self.RT.Get_Totaltime(filepath, ACO = True, OPT = True, IMP = True) #unit: second
File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/relaxtime.py", line 362, in Get_Totaltime
self.ACO.Get_Avgacotime(filepath)
File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/relaxtime.py", line 143, in Get_Avgacotime
self.Get_relaxtimefun(filepath)
File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/relaxtime.py", line 135, in Get_relaxtimefun
self.Get_elastconst(filepath + 'elastic/')
File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/relaxtime.py", line 89, in Get_elastconst
self.Elastic.Get_AvgLongEConst(filepath)
File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/elastic.py", line 49, in Get_AvgLongEConst
self.Get_ElasConst(filepath)
File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/AICON-2.1.0-py3.10.egg/aicon/elastic.py", line 45, in Get_ElasConst
outcar.read_elastic_tensor()
File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/pymatgen/io/vasp/outputs.py", line 2501, in read_elastic_tensor
et_table = self.read_table_pattern(header_pattern, row_pattern, footer_pattern, postprocess=float)
File "/home/hyj/soft/atomate/atomate_env/lib/python3.10/site-packages/pymatgen/io/vasp/outputs.py", line 2224, in read_table_pattern
retained_data = tables[-1] if last_one_only or first_one_only else tables
IndexError: list index out of range

**Comment by yjhao11** [comment]
Thank you very much!

**Comment by yociftci-ux** [comment]
parse_EIGENVAL_VASP energies.append(float(line.split()[1])*ev2h) IndexError: list index out of range.

**Comment by yociftci-ux** [comment]
AICON --elec -m standard -t 300
Traceback (most recent call last):
  File "/arf/home/yciftci/.local/bin/AICON", line 83, in <module>
    Get_Electron("./", Temp, Dope, mode, ifSB)
  File "/arf/home/yciftci/.local/bin/AICON", line 44, in Get_Electron
    Compound.Get_values(filepath, Temp, dope, mode, ifSB=ifSB)
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/electron.py", line 227, in Get_values
    CBM_Elcond, CBM_Seebeck, CBM_Lorenz, CBM_Ekappa, CBM_Hallfactor, CBM_Hallcoeff, CBM_PF) = self.CBM.Get_transport_para(filep
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/band.py", line 159, in Get_transport_para
    self.RT.Get_Totaltime(filepath, ACO = True, OPT = True, IMP = True)
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/relaxtime.py", line 362, in Get_Totaltime
    self.ACO.Get_Avgacotime(filepath)
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/relaxtime.py", line 143, in Get_Avgacotime
    self.Get_relaxtimefun(filepath)
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/relaxtime.py", line 136, in Get_relaxtimefun
    self.Get_effemass(filepath)
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/relaxtime.py", line 79, in Get_effemass
    self.EMC.cal_effmass(kpt, stepsize, band, prg, basis, filepath+'EIGENVAL')
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/myemc.py", line 507, in cal_effmass
    energies = self.parse_EIGENVAL_VASP(output_fh, band, len(st))
  File "/arf/home/yciftci/.local/lib/python3.9/site-packages/aicon/myemc.py", line 372, in parse_EIGENVAL_VASP
    energies.append(float(line.split()[1])*ev2h)
IndexError: list index out of range
