### ISSUE TITLE
Error Get_CBM

### ISSUE THREAD

**Issue by pshatom** [Baijianlu/AICON2#8]
Hello, I'm getting follwing error after running AICON - could you please suggest how to resolve this?

(base) [prs221@sol electron]$ AICON --elec -m standard --tmin 300 --tmax 1000 --tstep 50 --noSB

Traceback (most recent call last):
  File "/home/prs221/anaconda3/bin/AICON", line 4, in <module>
    __import__('pkg_resources').run_script('AICON==2.1.0', 'AICON')
  File "/share/Apps/lusoft/opt/spack/linux-centos8-haswell/gcc-8.3.1/py-setuptools/50.3.2-riojqp7/lib/python3.8/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/share/Apps/lusoft/opt/spack/linux-centos8-haswell/gcc-8.3.1/py-setuptools/50.3.2-riojqp7/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/home/prs221/anaconda3/lib/python3.7/site-packages/AICON-2.1.0-py3.7.egg/EGG-INFO/scripts/AICON", line 83, in <module>
  File "/home/prs221/anaconda3/lib/python3.7/site-packages/AICON-2.1.0-py3.7.egg/EGG-INFO/scripts/AICON", line 44, in Get_Electron
  File "/home/prs221/anaconda3/lib/python3.7/site-packages/AICON-2.1.0-py3.7.egg/aicon/electron.py", line 216, in Get_values
  File "/home/prs221/anaconda3/lib/python3.7/site-packages/AICON-2.1.0-py3.7.egg/aicon/electron.py", line 123, in Get_CBM
AttributeError: 'list' object has no attribute 'frac_coords'

**Comment by Baijianlu** [comment]
Hello,


Most probably, this problem is because your calculating object is a metal. Therefore, pymatgen cannot find CBM or VBM. You can plot its band structure to check.


________________________________
From: Prince Sharma ***@***.***>
Sent: 08 January 2023 14:53:20
To: Baijianlu/AICON2
Cc: Subscribed
Subject: [Baijianlu/AICON2] Error Get_CBM (Issue #8)


Hello, I'm getting follwing error after running AICON - could you please suggest how to resolve this?

(base) ***@***.*** electron]$ AICON --elec -m standard --tmin 300 --tmax 1000 --tstep 50 --noSB

Traceback (most recent call last):
File "/home/prs221/anaconda3/bin/AICON", line 4, in
import('pkg_resources').run_script('AICON==2.1.0', 'AICON')
File "/share/Apps/lusoft/opt/spack/linux-centos8-haswell/gcc-8.3.1/py-setuptools/50.3.2-riojqp7/lib/python3.8/site-packages/pkg_resources/init.py", line 650, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/share/Apps/lusoft/opt/spack/linux-centos8-haswell/gcc-8.3.1/py-setuptools/50.3.2-riojqp7/lib/python3.8/site-packages/pkg_resources/init.py", line 1453, in run_script
exec(script_code, namespace, namespace)
File "/home/prs221/anaconda3/lib/python3.7/site-packages/AICON-2.1.0-py3.7.egg/EGG-INFO/scripts/AICON", line 83, in
File "/home/prs221/anaconda3/lib/python3.7/site-packages/AICON-2.1.0-py3.7.egg/EGG-INFO/scripts/AICON", line 44, in Get_Electron
File "/home/prs221/anaconda3/lib/python3.7/site-packages/AICON-2.1.0-py3.7.egg/aicon/electron.py", line 216, in Get_values
File "/home/prs221/anaconda3/lib/python3.7/site-packages/AICON-2.1.0-py3.7.egg/aicon/electron.py", line 123, in Get_CBM
AttributeError: 'list' object has no attribute 'frac_coords'
