### ISSUE TITLE
IndexError: index 3 is out of bounds for axis 1 with size 3

### ISSUE THREAD

**Issue by MLK1998** [Baijianlu/AICON2#9]
Dear devlopers,
I want to calculate the phonon properties of a model, but the following error occurs after running the program according to the user manual. Can you help me with this? Thanks!

[inf inf inf inf]
[1246.57232686 2887.67975262 3685.46878087  263.47054931]
[114.16307004 114.16307004 129.94178566 150.79789137]
[0.82376162 1.20729785 1.83222916 3.14211823]
/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/aicon/phonon.py:57: RuntimeWarning: invalid value encountered in double_scalars
/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/aicon/phonon.py:157: IntegrationWarning: The occurrence of roundoff error is detected, which prevents the requested tolerance from being achieved.  The error may be underestimated.
/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/aicon/phonon.py:60: RuntimeWarning: invalid value encountered in double_scalars
/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/aicon/phonon.py:158: IntegrationWarning: The occurrence of roundoff error is detected, which prevents the requested tolerance from being achieved.  The error may be underestimated.
/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/aicon/phonon.py:66: RuntimeWarning: invalid value encountered in double_scalars
/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/aicon/phonon.py:170: IntegrationWarning: The occurrence of roundoff error is detected, which prevents the requested tolerance from being achieved.  The error may be underestimated.
/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/aicon/phonon.py:69: RuntimeWarning: invalid value encountered in double_scalars
/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/aicon/phonon.py:171: IntegrationWarning: The occurrence of roundoff error is detected, which prevents the requested tolerance from being achieved.  The error may be underestimated.
/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/aicon/phonon.py:183: RuntimeWarning: divide by zero encountered in double_scalars
/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/aicon/phonon.py:185: RuntimeWarning: invalid value encountered in double_scalars

**Comment by Baijianlu** [comment]
Hi,


This should because you didn't use the high symmetry path as AICON suggest. You should use "AICON --phon -p" to generate the high symmetry path, then use it to get the phonon spectrum and gruneisen parameters.




________________________________
From: MLK1998 ***@***.***>
Sent: 03 July 2023 21:33:47
To: Baijianlu/AICON2
Cc: Subscribed
Subject: [Baijianlu/AICON2] IndexError: index 3 is out of bounds for axis 1 with size 3 (Issue #9)


I want to calculate the phonon properties of a model, and the following error occurs after running the program according to the manual. Can you help me with this. Thanks!

Traceback (most recent call last):
File "/usr/local/bin/AICON", line 4, in
import('pkg_resources').run_script('AICON==2.1.0', 'AICON')
File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 658, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 1445, in run_script
exec(script_code, namespace, namespace)
File "/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/EGG-INFO/scripts/AICON", line 107, in
File "/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/EGG-INFO/scripts/AICON", line 51, in Get_Phonon
File "/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/aicon/phonon.py", line 141, in Get_Kappa
File "/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/aicon/phonon.py", line 90, in Get_Para
File "/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/aicon/tools.py", line 389, in Get_GVD
File "/usr/local/lib/python3.7/dist-packages/AICON-2.1.0-py3.7.egg/aicon/tools.py", line 295, in calc_MGV
IndexError: index 3 is out of bounds for axis 1 with size 3
